### PR TITLE
Evaluator 6 cards

### PR DESCRIPTION
**Pull request by zj8487**
#13

### CODE REVIEW

**Comment by zj8487** [comment]
@chenosaurus  ping

**Comment by zj8487** [comment]
please kindly update npm module, thanks a lot

**Comment by zj8487** [comment]
@chenosaurus 
npm package is outdate, please kindly update.
thanks a lot

**Comment by chenosaurus** [comment]
Sorry.  I will do so asap.

**Comment by zj8487** [comment]
@chenosaurus 
ping

**Comment by zj8487** [comment]
@chenosaurus 
ping

**Comment by zj8487** [comment]
@chenosaurus 
ping

**Pull request merged**
